version: "3.0"
services:
  arangodb:
    image: arangodb:3.6
    hostname: arangodb
    container_name: arangodb
    ports:
      - "8529:8529"
    environment:
      ARANGO_ROOT_PASSWORD: arangodb
      ARANGO_STORAGE_ENGINE: rocksdb
    volumes:
      - ./db/arango:/var/lib/arangodb3:delegated
  iso:
    container_name: iso
    build:
      context: .
    links:
      - arangodb
    ports:
      - "5000:5000"
      - "3035:3035"
    command: ["./scripts/wait-for-it.sh", "arangodb:8529", "--", "./scripts/start_app.sh"]
    volumes:
      - ./:/usr/src/app:delegated
